### ISSUE TITLE
Parse headers

### ISSUE THREAD

**Issue by Devatoria** [GoGoupil/goupil#8]
Parse HTTP response headers and store them into a `map[string]string`.

**Comment by Devatoria** [comment]
Commit on http: 3434a6abc8b144faa574db0bc80feb704a334bbd

**Comment by Wikigoagec** [comment]
> Parse HTTP response headers and store them into a `map[string]string`.
> 

http://architectshack.com/PoorMansTSqlFormatter.ashx
